### ISSUE TITLE
olsrd-mdp: create new connection to commotiond for each command execution

### ISSUE THREAD

**Issue by dismantl** [opentechinstitute/olsrd#17]
having one persistent connection to commotiond breaks CSM when commotiond is restarted. We should have both olsrd-mdp and CSM create new connections to commotiond for each command execution

**Comment by hawkinswnaf** [comment]
This is a good idea for a few reasons. Besides the one stated, we can get rid of a global variable!

**Comment by hawkinswnaf** [comment]
Build off the serval-plugin branch in my fork. To test, stop olsrd (/etc/init.d/olsrd stop) and then run it from the command line:
olsrd -d 3 -nofork -c /var/etc/olsrd.conf

and look for output that says something like "packet internally validated".

**Comment by areynold** [comment]
@hawkinswnaf, @elationfoundation's latest commits fixed the issue we were seeing during testing. Packets are validating internally. If you set up a pull request I will merge your changes.

**Comment by hawkinswnaf** [comment]
Awesome! Merge away!

**Comment by areynold** [comment]
merged.

**Comment by areynold** [comment]
@dismantl, @hawkinswnaf, is this issue fixed now?

**Comment by hawkinswnaf** [comment]
I do believe that it is. This should have been fixed in d6aa04a9884e4d8f8297e7802bfa16bd8a3f6101. 

@areynold merged it yesterday iirc.
