### ISSUE TITLE
DNS-SD plugin failing to pass multicast traffic in v0.6.6

### ISSUE THREAD

**Issue by jheretic** [opentechinstitute/olsrd#23]
After the upgrade to v0.6.6, the dnssd plugin no longer seems to be passing multicast traffic across the network. The plugin will need to be refactored in order to take into account changes in the new version.

**Comment by jheretic** [comment]
Assigning this to @dismantl and updating its status, since I know he's already working on it.

**Comment by dismantl** [comment]
The issues seen were not caused by DNSSD.
