### ISSUE TITLE
 Apparent OLSR sensitivity to node local time

### ISSUE THREAD

**Issue by areynold** [opentechinstitute/olsrd#9]
I'm starting this as a separate thread, in case the problem also arises for the folks testing on Android.

I've found that if a repeater node boots up with its local time grossly out of sync (ath5k devices especially), and it is unable to sync its local time via ntpdate, then it may not find its gateway route and thus not pass any client traffic. The node will still be accessible to SSH from other nodes on the mesh, so you can login manually to set a default route and update local time, but the OLSR assignment of default route appears to fail until local time is updated.

A further complication is that a repeater node with badly out-of-sync local time seems to also cause neighboring repeater nodes to also not find their default route, i.e. spreading the problem to more than one node. This problem, as I've observed it, is extremely sporadic. E.g. rebooting all nodes in the mesh can fix it.

The best measure I've found to avoid the problem is to use the OLSR SmartGateway feature, which Commotion OpenWRT does, along with a recurring ntpdate job that periodically sync the node's local time. That is, if ntpdate doesn't succeed on boot-up due to no Internet access, it will run again (and again) after a few minutes, until the gateway node is available.

(The Commotion images I published in a comment to issue #308 do this.)

I had posed this question on the olsr-users listserv a while back, although no one was quite sure what caused the problem. OLSRd itself shouldn't have a hard dependency on whether the node's local time is in sync.

Finally, do please note this problem is not unique to Commotion. I've experienced it on mesh nodes running ROBIN for atheros (OLSRd v0.5.6-r8) and plain vanilla OpenWRT Backfire v10.03.1 for ar71xx (OLSRd v0.6.1-3).

(Was issue 331 on code.commotionwireless.net)

**Comment by westbywest** [comment]
This problem relates to the olsrd-mod-secure plugin (which is quite obsolete).  OLSRd developers recommend using IBSS-RSN adhoc encryption at the link layer instead.

**Comment by areynold** [comment]
Oh awesome. 

Unfortunately it sounds like we may have reintroduced this issue in our olsr-mdp plugin, since it embeds a timestamp as partial protection against replay attacks.

Removing the upstream label. But leaving the issue open for further testing.

**Comment by westbywest** [comment]
An ugly hack that may work is to scan files in /etc/\* on boot, or wherever relevant, and extract the most recent modification date.  Then set local time to that datetime, if local time is older.  This would depend on just how large of a time offset olsrd-mod-mdp will tolerate.

Here is /etc/rc.local with said ugly hack, in use on TP-Link TL-MR3020's, which don't preserve local time across reboot.  You would likely want to add an if statement first verifying whether the local time is indeed older.

```
# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.

# Get date/time components of most recent filemod under /etc/update
FILELISTING=`ls -lr -u -e /etc/ | tail -1`
[ -n "${FILELISTING}" ] && {
    FILEMOD_YYYY=`echo $FILELISTING | awk '{printf "%d", $10}'`
    FILEMOD_HHMMSS=`echo $FILELISTING  | awk '{printf "%s", $9}'`
    FILEMOD_DD=`echo $FILELISTING | awk '{printf "%s", $8}'`
    FILEMOD_MONTH=`echo $FILELISTING | awk '{printf "%s", $7}'`

    # Convert Month to numerical MM format
    case "${FILEMOD_MONTH}" in
        "Jan") FILEMOD_MM="01" ;;
        "Feb") FILEMOD_MM="02" ;;
        "Mar") FILEMOD_MM="03" ;;
        "Apr") FILEMOD_MM="04" ;;
        "May") FILEMOD_MM="05" ;;
        "Jun") FILEMOD_MM="06" ;;
        "Jul") FILEMOD_MM="07" ;;
        "Aug") FILEMOD_MM="08" ;;
        "Sep") FILEMOD_MM="09" ;;
        "Oct") FILEMOD_MM="10" ;;
        "Nov") FILEMOD_MM="11" ;;
        "Dec") FILEMOD_MM="12" ;;
        *) FILEMOD_MM="01" ;;
    esac

    # Set local date/time, assuming format "YYYY-MM-DD hh:mm:ss"
    DATE="${FILEMOD_YYYY}-${FILEMOD_MM}-${FILEMOD_DD} $FILEMOD_HHMMSS"
    date -s "${DATE}"
}
```

**Comment by dismantl** [comment]
@jheretic and @areynold, should we implement this (or a modification of it)? Presumably if we have a user flash a node and use a commotion profile with olsrd-mdp turned on, it will fail to mesh with other nodes that have a gateway and thus an updated local time.

**Comment by jheretic** [comment]
Yes, it would be good to test out a version of this script. All we need to do is to get the timestamp somewhere in the ballpark for olsrd-mdp to not freak out.

**Comment by hawkinswnaf** [comment]
Not that it particularly matters, but if you look at the source of olsrd-mdp you can see exactly how close the timestamps need to be. From my quick glance, it appears to be the UPPER/LOWER_DIFF and SKEW values defined in olsrd_mdp.h on lines 72-76.

**Comment by jheretic** [comment]
I'm vaguely recalling that I don't think it's the actual timestamp handling in the plugin that's the problem. I think OLSRd just has issues with widely skewed timestamps in general, in that there's an error check somewhere in the code that rejects timestamps that are older than some really large value, like 10 years.

**Comment by hawkinswnaf** [comment]
Before closing this for good, I recommend testing. Iirc olsrd-mdp is actually quite sensitive to time differences. This is more than just olsrd sensitivity. I have run into this quite often in testing.

**Comment by critzo** [comment]
@hawkinswnaf do you have any thoughts on more robust tests to run through?

**Comment by technosopher** [comment]
Are we talking about sensitivities that are sufficiently granular that
we may need to think about implementing some sort of mesh time
synchronization system (perhaps as part of commotiond)?  Or can
timestamps be off by as much as, say, 24 hours?

**Comment by westbywest** [comment]
My own experience with this issue has never shown a problem with skew
between nodes with an active ntp client running.  (Also, I've had good
experience with the reliability of the ntp client already built into
OpenWRTs busybox.)  Rather, I've only seen this issue on newly powered-up
nodes, whose local time delta may be anywhere between -(several minutes)
and -(several years), and which need a route for their ntp client to
function.

On Fri, Dec 13, 2013 at 12:45 PM, technosopher notifications@github.comwrote:

> Are we talking about sensitivities that are sufficiently granular that
> we may need to think about implementing some sort of mesh time
> synchronization system (perhaps as part of commotiond)? Or can
> timestamps be off by as much as, say, 24 hours?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opentechinstitute/olsrd/issues/9#issuecomment-30533016
> .

## 

Ben West
me@benwest.name

**Comment by glamrock** [comment]
Perhaps there should be a config setting to set local time when setting up a node?

**Comment by jheretic** [comment]
@glamrock Apparently there's already an option to set the time from your browser in the LuCI admin page if it detects that it's different from the node's. Perhaps we could expose that in quickstart (if it isn't already).

@technosopher That's exactly the kind of middleware thing that I'd like commotiond to handle. However, distributed time synchronization is a potentially extremely tricky CS problem.
